### ISSUE TITLE
Introduction incomplete

### ISSUE THREAD

**Issue by Mte90** [MicroK-OS/microk#2]
Looking at https://github.com/MicroK-OS/microk/blob/master/doc/INTRODUCTION_TO_MICROK.md the file is incomplete and from the readme there are no instructions on how to try it (in a vm? cross compiling etc)

**Comment by FilippoMutta** [comment]
Yeah, I'll fix really soon.
 I'm currently sick rn, hopefully tomorrow I'll be able to complete it

**Comment by FilippoMutta** [comment]
> Looking at https://github.com/MicroK-OS/microk/blob/master/doc/INTRODUCTION_TO_MICROK.md the file is incomplete and from the readme there are no instructions on how to try it (in a vm? cross compiling etc)

The file has been updated with some basic instructions, allowing for normal compilation and testing. More in-depth explaination, with a deeper dive in the file structure of the repos and a bigger focus on expanding in non-x86 architectures coming soon.

**Comment by Mte90** [comment]
Right now is so much better and easy to understand :-)
Now the ticket can be closed as extend it is another thing compared to explain how to run it :-D
